# Data Preprocessing Tools

## Importing the libraries

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [6]:
dataset=pd.read_csv('Data.csv')
X=dataset.iloc[:,:-1].values  # Matrix of features
y=dataset.iloc[:,-1].values  # Vector of dependant variable

In [7]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [13]:
from sklearn.impute import SimpleImputer 
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3]) # a:b--> Include 'a' but EXCLUDE 'b'. Only till one less than b
X[:,1:3]=imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
X=np.array(ct.fit_transform(X)) #both sides must be "numpy" arrays only!
print(X)

NameError: name 'X' is not defined

Encode: Spain: 001, Germany= 010, France= 100; They are binary vectors, not necessarily binary representation
Remainder "passthrough" means keep other columns also 
Here, fit and transform is done in a single operation: fit_transform 

### Encoding the Dependent Variable

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=np.array(le.fit_transform(y))
print(y)

[0 1 0 0 1 1 0 1 0 1]
[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]
[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


We have to split both X and y into training and data set so it will result in 4 new variables. 
Test size =0.2 means 80% training and 20% test, which is recommended.
Random state is not really required

## Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:5]=sc.fit_transform(X_train[:,3:5])
X_test[:,3:5]=sc.fit_transform(X_test[:,3:5])
print(X)
print("......");
print(X_train);
print("......");
print(X_test);

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
......
[[1.0 0.0 0.0 1.2909944487358056 -0.19159184384578545 52000.0]
 [1.0 0.0 1.0 -0.7745966692414834 -0.014117293757057777 63777.77777777778]
 [0.0 1.0 0.0 -0.7745966692414834 0.566708506533324 72000.0]
 [1.0 0.0 0.0 1.2909944487358056 -0.30453019390224867 61000.0]
 [1.0 0.0 0.0 1.2909944487358056 -1.9018011447007988 48000.0]
 [0.0 1.0 0.0 -0.7745966692414834 1.1475343068237058 79000.0]
 [1.0 0.0 1.0 -0.7745966692414834 1.4379472069688968 83000.0]
 [0.0 1.0 0.0 -0.7745966692414834 -0.7401495441200351 58000.0]]
......
[[1.0 0.0 1.0 0.0 -1.0 54000.0]
 [0.0 1.0 0.0 0.0 1.0 67000.0]]


Feature scaling has 2 types: Standardization: (x-mean(x))/(std(x) 
                             Normalization: (x-min(x))/(max(x)-min(x))
Here we are using standardization, usually we get values between -3/-2 and 2/3